# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI
env:
  BUILD_TARGET: DEFAULT
  NEXT_PUBLIC_SUPABASE_URL: http://localhost:54321
  NEXT_PUBLIC_SUPABASE_ANON_KEY: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24iLCJleHAiOjE5ODM4MTI5OTZ9.CRXP1A7WOeoJeXxjNni43kdQwgnWNReilDMblYTn_I0'
  NEXT_PUBLIC_API_ENDPOINT: https://localhost:8000/my-local-postgres-api
  NEXT_PUBLIC_BASE_URL: http://localhost:3000
  NEXT_TELEMETRY_DISABLED: '1'
  #mapbox related
  NEXT_PUBLIC_MAPBOX_TREES_TILESET_LAYER: layer-name-within-tileset
  NEXT_PUBLIC_MAPBOX_TREES_TILESET_URL: mapbox://{username}.{tilesetId}
  NEXT_PUBLIC_MAPBOX_API_KEY: pk.123.xyz
  # if you are not in Berlin change these below
  NEXT_PUBLIC_MAP_BOUNDING_BOX: 13.0824446341071,52.3281202651866,13.7682544186827,52.681600197973
  NEXT_PUBLIC_MAP_INITIAL_LATITUDE: 52.500869
  NEXT_PUBLIC_MAP_INITIAL_LONGITUDE: 13.419047
  NEXT_PUBLIC_MAP_INITIAL_ZOOM: 11
  NEXT_PUBLIC_MAP_INITIAL_ZOOM_MOBILE: 13
  # data generated by the harvester
  NEXT_PUBLIC_RAIN_DATA_URL: https://tsb-trees.s3.eu-central-1.amazonaws.com/weather_light.geojson.gz
  NODE_ENV: test

on:
  push:
    branches: [master, staging]
  pull_request:
    branches: [master, staging]
    paths:
      - '.nvmrc'
      - 'src/**/*'
      - 'pages/**/*'
      - '.storybook/**/*'
      - 'public/**/*'
      - '.github/workflows/**/*'
      - 'package*.json'
      - 'jest.config.js'
      - 'tsconfig.json'
      - '.eslintrc.json'
      - 'next.config.js'
      - '*.js'
      - '*.cjs'
jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js from .nvmrc
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - run: npm ci
      - run: npm run build --if-present
      - run: npm run lint
      - run: npm run type-check
      - run: npm run test:ci
  release:
    name: semantic-release
    needs: [build]
    runs-on: ubuntu-latest
    outputs:
      new-release-published: ${{ steps.semantic-release.outputs.new_release_published }}
      new-release-version: ${{ steps.semantic-release.outputs.new_release_version }}
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - run: npm ci
      - id: semantic-release
        uses: cycjimmy/semantic-release-action@v3
        with:
          semantic_version: 18
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
